name: Truffle Build

env:
#  WALLET_SECRET: ${{ secrets.DEV_WALLET_SECRET }} # Set Deployer wallet secret using GitHub secrets
  RPC: https://localhost:8545 # Testnet RPC
  NETWORK_ID: "*" # Testnet Network ID
#  CONFIRMATIONS: 1 # Confirmation blocks required

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out the source code
      uses: actions/checkout@v2
    
    - name: Setup NodeJS 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Show NodeJS version    
      run: npm --version
    
    #- name: Create .env file
    #  run: echo "${{ secrets.DOT_ENV }}" > .env

    - uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('./packages-lock.json') }}

    - name: Install Truffle
      run: npm install truffle -g
    
    - name: Install Truffle Dependencies
      run: npm install      
    
    - name: Run Truffle Test  
      run: truffle test

    - name: Start a Ganache-Cli server in background
      run: ./node_modules/.bin/ganache-cli &
      
    - name: Run Test Coverage
      run: truffle run coverage
